### ISSUE TITLE
[Improvement] Edit command is unable to edit the right tag for persons with multiple tags 

### ISSUE THREAD

**Issue by miuna9890** [AY2425S1-CS2103T-W13-1/tp#146]
for instance if a person has t/class3 and t/class4 when we [edit t/class5] both the tags are deleted and changed to class 5 which should not be the right behavior. We could have a prompt for which tag to delete similar to delete function or limit tags to just one per person if needed

**Comment by zhou-colla** [comment]
v1.6 wrap up
