### ISSUE TITLE
[Improvement] Delete command - delete 0 could return the same error message as for other invalid indexes

### ISSUE THREAD

**Issue by miuna9890** [AY2425S1-CS2103T-W13-1/tp#148]
delete 0 returns 'index is not a non-zero unsigned integer...' which does not seem very user friendly. Possible return the same error message 'person index not valid'

also for all invalid param like [delete knek]  'index is not a non-zero unsigned integer...' is shown instead of the invalid format message indicating the right format

**Comment by zhou-colla** [comment]
v1.6 wrap up
