### ISSUE TITLE
[Bug] Wrong error message for find command

### ISSUE THREAD

**Issue by miuna9890** [AY2425S1-CS2103T-W13-1/tp#191]
![image](https://github.com/user-attachments/assets/c65e44ec-01c0-4d4d-b640-b12ca48e13bd)

Spelling errors. also the message dosent say u can find by INDEX but we actually can. so should edit the message accordingly

**Comment by yyueyii** [comment]
<img width="899" alt="Screenshot 2024-11-09 at 11 50 22 PM" src="https://github.com/user-attachments/assets/3c734167-fe17-4261-96e3-44461c949b62">

can I change to this?
