### ISSUE TITLE
[Bug] Find command for find by address is not case insensitive and searching is inconsistent

### ISSUE THREAD

**Issue by miuna9890** [AY2425S1-CS2103T-W13-1/tp#192]
if i have a person with address - Pungol, find a/pungol shows 0 person listed. The same for email. It is case sensitive but searching has gotta be case insensitive i think

Also the email and phone numbers , role and address all doesent allow partial search but name does. I think better to keep it consisent or maybe make the UG more detailed so that it is not pointed out as a bug

**Comment by zhou-colla** [comment]
v1.6 wrap up
