### ISSUE TITLE
[Improvement] Usage description of batch edit

### ISSUE THREAD

**Issue by haleemairfan** [AY2425S1-CS2103T-W13-1/tp#203]
<img width="698" alt="Screenshot 2024-11-10 at 06 56 33" src="https://github.com/user-attachments/assets/4d091d9f-1dfd-42ca-b37c-32defdb5b665">
This explanation could be more non technical user friendly. instead of using tagParameters could just say change the specified tag t/OLDTAG to the new one t/NEWTAG

**Comment by yyueyii** [comment]
I think Parameters:... is supposed to be on the next line. I have added a line break

**Comment by zhou-colla** [comment]
v1.6 wrap up
