### ISSUE TITLE
Add parsing prefix for delete command IN PROGRESS(v1.3)

### ISSUE THREAD

**Issue by miuna9890** [AY2425S1-CS2103T-W13-1/tp#65]
The current idea I have in mind is adding prefixes. For example, the command is able to parse all the prefixes and the user have to supply a minimum of 1 prefix and value such as delete i/[index].

When the user write delete n/John a/nus lmao, it will narrow the delete and I think this prefix mechanism can be extended further for batch delete and such.

_Originally posted by @MinkhantEain in https://github.com/AY2425S1-CS2103T-W13-1/tp/pull/63#discussion_r1795655214_

**Comment by MinkhantEain** [comment]
Revert back to delete by index only.
